### ISSUE TITLE
Prowadzenie warsztatu

### ISSUE THREAD

**Issue by afronski** [silesian-beamers/interactive-tetris#2]
@michalmuskala @mentero Jak prowadzić taki warsztat?

Ja widzę dwie ścieżki:
- Tagi i branche w `git`.
  - Pewien poziom zbudowanej aplikacji jest reprezentowany jako tag w `git`.
  - Zadania polegają na wykonaniu czegoś, namieszaniu w kodzie, potem `git reset . && git checkout NEXT_TAG` - i następne zadanie.
- Wszyscy budują to samo z ekranu, jeśli komuś się nie uda lub będzie robił inaczej - łatamy na żywo.
  - Spontaniczna opcja, niosąca ze sobą duże ryzyko potencjalnych problemów.

**Comment by michalmuskala** [comment]
Wydaje mi się, że opcja pierwsza jest znacznie lepsza, pozwoli nam być bardziej elastycznym. 
Szczególnie przy tak długim warsztacie zostawienie kogoś z tyłu było by dużym problemem.

**Comment by afronski** [comment]
Idziemy w tagi na `git`.
